import type { Metadata, Viewport } from 'next'
import { Inter, Unbounded } from 'next/font/google'

import '../styles/global.scss'

const inter = Inter({
	subsets: ['cyrillic'],
	display: 'swap',
	weight: '400',
	variable: '--font-inter',
})

const unbounded = Unbounded({
	subsets: ['cyrillic'],
	display: 'swap',
	weight: '900',
	variable: '--font-unbounded',
})

export const viewport: Viewport = {
	themeColor: '#212327',
}

export const metadata: Metadata = {
	title: 'NextWave IT Group',
	description: 'Generated by create next app',
	referrer: 'strict-origin',
	icons: [
		{
			rel: 'icon',
			type: 'image/x-icon',
			url: '/favicon.ico',
		},
		{
			rel: 'shortcut icon',
			type: 'image/x-icon',
			url: '/favicon.ico',
		},
		{
			rel: 'icon',
			type: 'image/png',
			url: '/favicon-16x16.png',
			sizes: '16x16',
		},
		{
			rel: 'icon',
			type: 'image/png',
			url: '/favicon-32x32.png',
			sizes: '32x32',
		},
		{
			rel: 'apple-touch-icon',
			url: '/apple-touch-icon.png',
		},
		{
			rel: 'manifest',
			url: '/site.webmanifest',
		},
	],
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html
			lang='ru'
			className={`${inter.variable} ${unbounded.variable} font-sans`}
		>
			<body className='font-inter'>{children}</body>
		</html>
	)
}
