import type { Metadata } from 'next'
import { Inter, Unbounded } from 'next/font/google'

import '../styles/global.scss'

const inter = Inter({
	subsets: ['cyrillic'],
	display: 'swap',
	weight: '400',
	variable: '--font-inter',
})

const unbounded = Unbounded({
	subsets: ['cyrillic'],
	display: 'swap',
	weight: '900',
	variable: '--font-unbounded',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html
			lang='ru'
			className={`${inter.variable} ${unbounded.variable} font-sans`}
		>
			<body className='font-inter'>{children}</body>
		</html>
	)
}
